# Generated by Django 6.0.3 on 2026-03-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('issuing_organization', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('club', 'Club / Society'), ('sport', 'Sports'), ('volunteer', 'Volunteering'), ('event', 'Event / Hackathon'), ('other', 'Other')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('journal_or_conference', models.CharField(max_length=300)),
                ('publication_date', models.DateField()),
                ('abstract', models.TextField(blank=True)),
                ('paper_link', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
